### ISSUE TITLE
Config options to disable machines

### ISSUE THREAD

**Issue by Yarden-zamir** [Magneticraft-Team/Magneticraft#108]
For now, I'm using ct but I'd like it to be native if that's possible.

**Comment by cout970** [comment]
If you want to disable the water generator you can change the production amount in the config. 
I not sure what you mean by disabling machines, you can remove the crafting recipe, make the TileEntities not tick, or remove the block (which is not plausible because it breaks worlds).

Also if you can disable the blocks with CT then I think a native method is not needed. Adding an option to disable every machine is a lot of work and maybe it's not worth.
