### ISSUE TITLE
Magneticraft items do not appear when searched for in the creative menu

### ISSUE THREAD

**Issue by WrongWeekend** [Magneticraft-Team/Magneticraft#119]
If I search for a Magneticraft item in the creative menu, it does not appear:

https://i.imgur.com/DZPSHmI.png

I can only get it by accessing the Magneticraft tab directly and looking for the item there:

https://i.imgur.com/k7WTE0i.png

**Comment by cout970** [comment]
I think I know what causes it. it just requires to change the startup code of the mod to use the new (not that new anymore) forge registries.

The problem is that this code is mixed between item/block registration and recipe registration so I need to find a way to sort them. This shouldn't be too hard to fix , but I have no time this weeks
