### ISSUE TITLE
Rendering performance issue with Magneticraft.

### ISSUE THREAD

**Issue by ghost** [Magneticraft-Team/Magneticraft#137]
I've been annoyed recently by huge FPS drop when looking in general direction of my friend's base and couldn't find what is the cause of this issue.

I'm sure Magneticraft isn't solely responsible, but while looking from a bit further I've noticed what you can see in this video:

https://youtu.be/PeEIC5wdNaE

That means each cable in magneticraft is rendered separately - which means (at least) one/two draw calls per cable block.

Thar is just crazy!

Why aren't cables  baked into chunk geometry like any other static block would be?

This begs the question: is every block in magneticraft rendered separately?

If so, that is just horribly wrong...

**Comment by cout970** [comment]
Idk what are you talking about, the mod only uses TileEntitySpecialRenderers only for stuff that needs animations or any kind of special rendering that cannot be achieved with simple chunk geometry baking. 
Also all models rendered in TESR are stored in GPU using Display lists so the draw calls are more efficient. 

Cables have TESR because the have to update it connections without the need of block updates. If you know a more efficient approach for cables, feel free to tell me how or make a PR.
