### ISSUE TITLE
Nonstandard OreDictionary

### ISSUE THREAD

**Issue by IdrisQe** [Magneticraft-Team/Magneticraft#140]
I suppose technically a minor issue, but one that has been giving me trouble for hours.

The OreDictionary entries used by Magneticraft seem very non-standard.
Examples being:
oreGalena for Lead Ore, when it should be oreLead to match other mods.
orePyrite when i think oreSulfur or oreSulphur would be more standard.
As well, they could be registered to both, similarly to how Immersive Engineering's Bauxite Ore is registered to both oreAluminum and oreBauxite.
blockLimestone instead of stoneLimestone, and each Limestone variant having its own unusual oredict entry, heavy and light plates instead of just plates (could make light plates the same as plates from other mods), etc.

This makes working compatability into a modpack tedious, as makers need to figure out what your oredict entries are called so they can be unified using InstantUnify or Unidict, etc. I'd suggest sticking to OreDictionary standards to ensure maximum compatability.

(On a side-note, apologies for the annoyed tone I had in the original post. I've been making a modpack over the last few days and it's been surprisingly stressful working out the massive number of kinks. That doesn't excuse the tone I took. I appreciate the work you all do on the mod, and even in it's early state it's easily one of my favourite tech mods due to the detail and features, and I look forward to seeing it grow more.)

**Comment by cout970** [comment]
Hi, thanks for taking your time and report an issue with the mod. The oreGalena is technically not lead, since is a mix of lead and silver, but I can register oreSilver and oreLead as extra OreDictionary entries.

I don't get why `stoneLimestone` is more standard than `blockLimestone` since forge registers `blockCactus`, `blockSlime`, `blockPrismarine`, `blockGlass`, etc.  Also forge doesn't add a prefix for cobble, for example granite can be `stoneGranite` or `stoneGranitePolished` instead of `cobbleGranite` and `stoneGranite` which would make more sense.

Let me know If you have any other suggestion for changing or adding OreDictionary entries.

**Comment by EternalPhane** [comment]
Excuse me, but what about those light and heavy plates? I noticed you mentioned "[Light plates from magneticraft and plates from other mods are meant to be different](https://github.com/Magneticraft-Team/Magneticraft/issues/84#issuecomment-372135690)", but I can't figure out how they're different since they're all made of a single metal ingot and cost some durability of some tools.

**Comment by eternalphane** [comment]
Excuse me, but what about oredict entries of those light and heavy plates? I've noticed you said "[Light plates from magneticraft and plates from other mods are ment to be different](https://github.com/Magneticraft-Team/Magneticraft/issues/84#issuecomment-372135690)", but I can't figure out how they're different since they're all made of a single metal ingot and cost some durability of some tools.

**Comment by IdrisQe** [comment]
Don't count on this being addressed. The mod has been discontinued, unfortunately.

![image](https://user-images.githubusercontent.com/40530630/47410750-9b09ce00-d71b-11e8-8c63-52efb41e71a4.png)
