### ISSUE TITLE
Shelving Unit inventory does not persist on relog

### ISSUE THREAD

**Issue by spenrathm** [Magneticraft-Team/Magneticraft#160]
See video:

https://v.redd.it/q8a0h70crr931

Project Ozone 3 v3.0.41

Magneticraft v2.6.5

**Comment by cout970** [comment]
I've commented in the reddit post, but I'm going to repeat it here:
I actually have no idea why they disappear, I'm technically saving the number of chests when the TileEntity is saved. 
Also in the last version 2.7.0 the GUI is fixed, can you test that bug in the latest version? Also what happens if you break the shelving unit does it drop the chests?

**Comment by cout970** [comment]
I tried this in my test world, but I was unable to replicate the bug, it could be a bad interaction with another mod in the pack or it's fixed in 2.7.0 I will wait for your input

**Comment by cout970** [comment]
Seems to be fixed in 2.7.0
