### ISSUE TITLE
Crafttweaker and Magneticraft

### ISSUE THREAD

**Issue by Rams59** [Magneticraft-Team/Magneticraft#175]
Hey o troed to change some recipes exactely like in the wiki, but its not working,
Are ther things changed?
Version is 1.12.8dev

**Comment by cout970** [comment]
The wiki should be updated, nothing has changed as far as I know.

Can you give me some examples of recipes that don't work?
Do you get any errors in the game's log?
Are you sure you are including the [MtLib](https://www.curseforge.com/minecraft/mc-mods/mtlib) required to use Crafttweaker recipes?

**Comment by Rams59** [comment]
I try to add a Recipe for normal Iron Plates from Thermal Expansion to the chrushing Table and get that Error:

[INITIALIZATION][CLIENT][ERROR] items_disabled.zs:153 > 2 methods available but none matches the parameters (ZenTypeNative: crafttweaker.oredict.IOreDictEntry, ZenTypeNative: crafttweaker.item.IIngredient[][])

what i added was:

mods.magneticraft.CrushingTable.addRecipe(<minecraft:iron_ingot>,<thermalfoundation:material:32> * 1, true);

The MtLib is included

**Comment by cout970** [comment]
That error indicates that the line 153 contains an error, which can cause the rest of lines to fail.

That example seems to be correct, I suspect that the error is in another recipe, because it's trying to call a method, that has two variations, and the arguments don't match any of the variants.
 
mods.magneticraft.CrushingTable.addRecipe only has 1 variant so it can't be the cause.

**Comment by Rams59** [comment]
line 153 is exactely this line. Thats why i dont understand it

**Comment by cout970** [comment]
can you share the script?
