### ISSUE TITLE
Crushing Table not processing other mod ores

### ISSUE THREAD

**Issue by tommyTT** [Magneticraft-Team/Magneticraft#5]
I have configured my game so that all the ores come from the Substratum mod including the copper and lead ores, but they can't be processed in the crushing table. I expect the same is true for all other ores from other mods (Silver, Zinc, Osmium, Tin, ...).

Versions:
Minecraft 1.10.2
Forge 12.18.1.2076
Magneticraft 1.0.0-release

**Comment by MechWarrior99** [comment]
We will ore dict register the recipes so that other mods copper, lead, cobalt, and tungsten will work. I am not sure if we will add support for all the others like we did last time, it was a lot of work to do them all, we may add support for the more common ores like silver and tin, not sure about the rest though.
