### ISSUE TITLE
Ores with default harvest level

### ISSUE THREAD

**Issue by tommyTT** [Magneticraft-Team/Magneticraft#6]
The ores all have the default harvest level and can be broken with a stone pickaxe. For copper and lead this is fine, for Tungsten I don't know, but for cobalt it is a no go. Cobalt is one of the high level materials from Tinkers and shouldn't be harvestable by a stone pick. 
In my opinion, the introduction of cobalt to the overworld is dangerous, because of the meaning of it in Tinkers. Since every pack seems to have that mod in, I would suggest looking at maybe using a different material alltogether.

**Comment by MechWarrior99** [comment]
Good point about the harvest levels, didn't even think about it tbh. They will be changed now I think.

About cobalt.
We are going to remove ours from the oreDictionary so that it will not mess up TCon Progression. Cobalt is used  IRL in things like rechargeable batteries. So it does not make sense to remove it, as we are going to be using it for things like that.
